#!/bin/bash

# Android build script for Xray-core
export ANDROID_NDK_HOME="/Users/jojo/Library/Android/sdk/ndk/29.0.14206865"
export GOOS=android
export CGO_ENABLED=1

# React Native Nitro output path
OUTPUT_DIR="../android/src/main"
LIBS_DIR="$OUTPUT_DIR/jniLibs"
INCLUDE_DIR="$OUTPUT_DIR/cpp"

mkdir -p "$INCLUDE_DIR"

# Define architectures to build
# Format: "JNI_DIR|GOARCH|GOARM|CLANG_PREFIX"
archs=(
    "arm64-v8a|arm64||aarch64-linux-android30"
    "armeabi-v7a|arm|7|armv7a-linux-androideabi30"
    # "x86_64|amd64||x86_64-linux-android30"
    # "x86|386||i686-linux-android30"
)

for arch_info in "${archs[@]}"; do
    IFS='|' read -r jni_arch go_arch go_arm clang_prefix <<< "$arch_info"
    
    echo "==========================================="
    echo "Building for $jni_arch..."
    
    mkdir -p "$LIBS_DIR/$jni_arch"
    
    export GOARCH="$go_arch"
    if [ -n "$go_arm" ]; then
        export GOARM="$go_arm"
    else
        unset GOARM
    fi
    
    export CC="$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/darwin-x86_64/bin/$clang_prefix-clang"
    export CXX="$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/darwin-x86_64/bin/$clang_prefix-clang++"
    
    go build -buildmode=c-shared -ldflags="-s -w -extldflags=-Wl,-soname,libxray.so" -o "$LIBS_DIR/$jni_arch/libxray.so" ./libxray
    
    if [ $? -eq 0 ]; then
        # The header generated by cgo depends on the target architecture (pointer size, int size).
        # We must keep separate headers for each architecture.
        mkdir -p "$INCLUDE_DIR/xray/$jni_arch"
        echo "Copying header file to architecture-specific include directory..."
        cp "$LIBS_DIR/$jni_arch/libxray.h" "$INCLUDE_DIR/xray/$jni_arch/"
        
        # Remove the generated header from the jniLibs folder so it doesn't get bundled in APK
        rm -f "$LIBS_DIR/$jni_arch/libxray.h"
        echo "$jni_arch build successful!"
    else
        echo "$jni_arch build failed!"
        exit 1
    fi
done

echo "==========================================="
echo "All builds completed successfully!"
