#!/usr/bin/env bun
/**
 * Generates `src/generated/core-versions.ts` from the SHIPPED native artifacts.
 *
 * Why not go.mod: go.mod is what the next build would use, not what the
 * committed binaries were built from. The Go linker embeds a build-info table
 * (`\xff Go buildinf:` + a `dep <module> <version>` list) into every artifact,
 * so the binaries carry their own ground truth. Reading it needs no Go
 * toolchain and no NDK — which matters, because the .so/.a here are prebuilt
 * and committed, and nothing in CI rebuilds them.
 *
 * All four shipped artifacts are scanned and required to agree. That assertion
 * is the whole safety net: it fails the build the moment someone rebuilds one
 * platform and forgets the other.
 */
import { readFileSync, mkdirSync, writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { pseudoVersionIdentity, xrayDisplayVersion } from '../src/versions/parse'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')

const ARTIFACTS = [
  'android/src/main/jniLibs/arm64-v8a/libxray.so',
  'android/src/main/jniLibs/armeabi-v7a/libxray.so',
  'ios/Xray.xcframework/ios-arm64/libxray.a',
  'ios/Xray.xcframework/ios-arm64-simulator/libxray.a',
]

const MODULES = {
  xray: 'github.com/xtls/xray-core',
  olcrtc: 'github.com/openlibrecommunity/olcrtc',
} as const

const OUT = join(ROOT, 'src/generated/core-versions.ts')

/**
 * Finds `dep\t<module>\t<version>` in the Go build-info table.
 *
 * Scans the Buffer directly rather than stringifying it — these artifacts are
 * 46-66 MB each and `toString()` on all four would allocate ~450 MB of string
 * on every build.
 */
function findDepVersion(buf: Buffer, module: string): string | null {
  const needle = Buffer.from(`dep\t${module}\t`, 'latin1')
  const at = buf.indexOf(needle)
  if (at === -1) return null
  const from = at + needle.length
  let to = from
  // The version runs to the next tab / newline / NUL / non-printable byte.
  while (to < buf.length) {
    const b = buf[to]!
    if (b <= 0x20 || b === 0x7f) break
    to++
  }
  const version = buf.toString('latin1', from, to)
  return version.length > 0 ? version : null
}

const seen = new Map<string, Map<string, string[]>>()

for (const rel of ARTIFACTS) {
  const buf = readFileSync(join(ROOT, rel))
  for (const [key, module] of Object.entries(MODULES)) {
    const version = findDepVersion(buf, module)
    if (!version) {
      throw new Error(
        `gen-core-versions: no build-info entry for ${module} in ${rel}. ` +
          `Was this artifact built from go-core/, or is the Go build-info table stripped?`
      )
    }
    const perKey = seen.get(key) ?? new Map<string, string[]>()
    perKey.set(version, [...(perKey.get(version) ?? []), rel])
    seen.set(key, perKey)
  }
}

const resolved: Record<string, string> = {}
for (const [key, byVersion] of seen) {
  if (byVersion.size !== 1) {
    const detail = [...byVersion]
      .map(([v, files]) => `  ${v}\n${files.map((f) => `    ${f}`).join('\n')}`)
      .join('\n')
    throw new Error(
      `gen-core-versions: shipped artifacts disagree on ${MODULES[key as keyof typeof MODULES]}:\n${detail}\n` +
        `Rebuild both platforms (go-core/build_android.sh and go-core/build_ios.sh) so they match.`
    )
  }
  resolved[key] = [...byVersion.keys()][0]!
}

const xrayModule = resolved.xray!
const olcrtcModule = resolved.olcrtc!
const xray = xrayDisplayVersion(xrayModule) ?? xrayModule
const { commit: olcrtc, date: olcrtcDate } = pseudoVersionIdentity(olcrtcModule)

const body = `// AUTO-GENERATED by scripts/gen-core-versions.ts — do not edit by hand.
// Extracted from the Go build-info table of the committed native artifacts,
// so these describe the binaries that actually ship, not go.mod's intent.
// Regenerate with \`bun run gen:versions\` after every Go rebuild.

/** Versions of the native cores linked into the shipped binaries. */
export interface CoreVersions {
  /** Xray-core, in \`core.Version()\` shape — e.g. "26.3.27". */
  xray: string
  /** Xray-core Go module version — e.g. "v1.260327.0". */
  xrayModule: string
  /**
   * olcrtc has no released semantic version; upstream is pinned by commit, so
   * the short commit hash is the only honest identifier — e.g. "1255cf8".
   */
  olcrtc: string
  /** olcrtc Go module pseudo-version — e.g. "v0.0.0-20260704192300-1255cf8248ee". */
  olcrtcModule: string
  /** Commit date behind the olcrtc pseudo-version, ISO \`YYYY-MM-DD\`. */
  olcrtcDate: string
}

export const CORE_VERSIONS: CoreVersions = {
  xray: ${JSON.stringify(xray)},
  xrayModule: ${JSON.stringify(xrayModule)},
  olcrtc: ${JSON.stringify(olcrtc)},
  olcrtcModule: ${JSON.stringify(olcrtcModule)},
  olcrtcDate: ${JSON.stringify(olcrtcDate)},
}
`

mkdirSync(dirname(OUT), { recursive: true })
writeFileSync(OUT, body)
console.log(
  `gen-core-versions: xray ${xray} (${xrayModule}), olcrtc ${olcrtc} (${olcrtcDate}) — ` +
    `${ARTIFACTS.length} artifacts agree`
)
